# backend/migrations/versions/0002_fix_chunks_cascade.py
"""Fix chunks.document_id FK to add ON DELETE CASCADE

This migration repairs the missing ON DELETE CASCADE constraint on
chunks.document_id. Without it, deleting a Document row does NOT cascade-
delete its chunks at the database level — orphaned chunk rows (and their
pgvector embeddings) pollute vector search indefinitely.

Revision ID: 0002_fix_chunks_cascade
Revises: 2ace56c6dd43
Create Date: 2026-03-23
"""
from alembic import op

revision = "0002_fix_chunks_cascade"
down_revision = "2ace56c6dd43"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Drop the existing FK constraint (no cascade rule)
    # Constraint name matches what was generated by the initial migration.
    # If yours differs, run:
    #   SELECT conname FROM pg_constraint WHERE conrelid = 'chunks'::regclass;
    op.drop_constraint(
        "chunks_document_id_fkey",
        "chunks",
        type_="foreignkey",
    )

    # Step 2: Re-add FK with ON DELETE CASCADE
    op.create_foreign_key(
        constraint_name="chunks_document_id_fkey",
        source_table="chunks",
        referent_table="documents",
        local_cols=["document_id"],
        remote_cols=["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    # Revert to FK without cascade (restores pre-fix state)
    op.drop_constraint(
        "chunks_document_id_fkey",
        "chunks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        constraint_name="chunks_document_id_fkey",
        source_table="chunks",
        referent_table="documents",
        local_cols=["document_id"],
        remote_cols=["id"],
        # No ondelete= intentionally — mirrors the broken original state
    )
