"""Init

Revision ID: 2ace56c6dd43
Revises: 
Create Date: 2026-03-18 17:49:21.776359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '2ace56c6dd43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_event', table_name='audit_logs')
    op.drop_index('idx_audit_query', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_query_log_id'), 'audit_logs', ['query_log_id'], unique=False)
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_chunks_document', table_name='chunks')
    op.drop_index('idx_chunks_embedding', table_name='chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_chunks_workspace', table_name='chunks')
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_workspace_id'), 'chunks', ['workspace_id'], unique=False)
    op.drop_index('idx_citations_query', table_name='citations')
    op.create_index(op.f('ix_citations_query_log_id'), 'citations', ['query_log_id'], unique=False)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'application/pdf'::text"))
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_workspace', table_name='documents')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.alter_column('query_logs', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_query_logs_user', table_name='query_logs')
    op.drop_index('idx_query_logs_workspace', table_name='query_logs')
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_query_logs_workspace_id'), 'query_logs', ['workspace_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::text"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('idx_workspaces_owner', table_name='workspaces')
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.create_index('idx_workspaces_owner', 'workspaces', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::text"))
    op.drop_index(op.f('ix_query_logs_workspace_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.create_index('idx_query_logs_workspace', 'query_logs', ['workspace_id'], unique=False)
    op.create_index('idx_query_logs_user', 'query_logs', ['user_id'], unique=False)
    op.alter_column('query_logs', 'model_used',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_index('idx_documents_workspace', 'documents', ['workspace_id'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'application/pdf'::text"))
    op.drop_index(op.f('ix_citations_query_log_id'), table_name='citations')
    op.create_index('idx_citations_query', 'citations', ['query_log_id'], unique=False)
    op.drop_index(op.f('ix_chunks_workspace_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.create_index('idx_chunks_workspace', 'chunks', ['workspace_id'], unique=False)
    op.create_index('idx_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_chunks_document', 'chunks', ['document_id'], unique=False)
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_audit_logs_query_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index('idx_audit_query', 'audit_logs', ['query_log_id'], unique=False)
    op.create_index('idx_audit_event', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
